name: Continuous Deployment

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed
    branches:
      - main

jobs:
  deployment:
    name: Deployment of ${{ github.ref_name }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    env:
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Deno (latest)
        uses: denoland/setup-deno@v1

      - name: Ahead-of-time Build
        run: deno task build

      - name: Upload to Deno Deploy
        run: |
          deno install -Arf jsr:@deno/deployctl
          deployctl deploy --prod --project=eserlive ./pkg/main/main.ts
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
